### ISSUE TITLE
FedRAMP High pulling from FedRAMP Moderate column

### ISSUE THREAD

**Issue by AMHesch** [salesforce/aws-allowlister#49]
The FedRAMP High scraper is pulling from the moderate column, you can tell from the fact it adds `chime`, `eks`, and a couple other services that are approved for moderate, but not high.

**Comment by kmcquade** [comment]
@AMHesch - thanks for pointing this out.

I saw you opened a PR to fix this (#47) but then you closed it. Any reason why?

**Comment by AMHesch** [comment]
Opened PR (#58 ) to fix and added unit test for FedRAMP High. Chose Chime for unit test as Chime is not installed in GovCloud.

**Comment by kmcquade** [comment]
Fixed by #58. Thanks so much! It looks great.
