### ISSUE TITLE
Upgrade homebrew formula to support version `0.2.10`

### ISSUE THREAD

**Issue by shirishp** [salesforce/aws-allowlister#97]
Version 0.2.10 was released on 27 September, but the homebrew formula still points to `0.2.9`.

```bash
❯ brew update
Updated 1 tap (homebrew/core).
No changes to formulae.

❯ brew info aws-allowlister
salesforce/aws-allowlister/aws-allowlister: stable 0.2.9
Shiny new formula
https://github.com/salesforce/aws-allowlister
/usr/local/Cellar/aws-allowlister/0.2.9 (2,572 files, 55MB) *
  Built from source on 2021-06-22 at 11:57:53
From: https://github.com/salesforce/aws-allowlister/blob/HEAD/HomebrewFormula/aws-allowlister.rb
==> Dependencies
Required: python3 ✘

```

**Comment by kmcquade** [comment]
@shirishp - this should be fixed now thanks to #88. Thanks @PatMyron for your help and thanks to everyone for your patience. I left Salesforce a few months ago so this fell by the wayside. The automation being back in place and fixed should make this easy to maintain again.
